In [8]:
import numpy as np
import torch

In [7]:
randseed1 = np.random.RandomState(seed=17)
randseed2 = np.random.RandomState(seed=15)

print(randseed1.randn(5))
print(randseed2.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.31232848  0.33928471 -0.15590853 -0.50178967  0.23556889]
[ 1.9819639   1.00959555  0.06789345 -1.00363598 -1.06193596]


### Random Generator in Pytorch


In [15]:
torch.randn(5)

torch.manual_seed(5)
print(torch.randn(5))

tensor([-0.4868, -0.6038, -0.5581,  0.6675, -0.1974])
