In [3]:
import numpy as np
import torch

### Using Numpy


In [8]:
# create vector
nv = np.array([[1, 2, 3, 4]])
print(nv)

# transpose vector
print(nv.T)


[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [12]:
# create matrix
nM = np.array([
    [1, 2, 3, 4], # row 1
    [3, 4, 5, 6] # row 2
])

print(nM), print()
print(nM.T)

[[1 2 3 4]
 [3 4 5 6]]

[[1 3]
 [2 4]
 [3 5]
 [4 6]]


### Using PyTorch


In [13]:
tv = torch.tensor([
    [1, 2, 3, 4] # row 1
])

print(tv)

print(tv.T)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [15]:
tM = torch.tensor([
    [1, 2, 3, 4], # row 1
    [3, 4, 5, 6] # row 2
])

print(tM)

print(tM.T)

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])
tensor([[1, 3],
        [2, 4],
        [3, 5],
        [4, 6]])
