In [1]:
import numpy as np
import torch
import torch.nn as nn

In [4]:
# Vector (numpy)
v = np.array([1, 40, 2, -3])

minval = np.min(v)
maxval = np.max(v)

print(minval, maxval)

min_idx = np.argmin(v)
max_idx = np.argmax(v)

print(min_idx, max_idx)

-3 40
3 1


In [10]:
# Matrix (numpy)

M = np.array([[0, 1, 10], [20, 6 , 5]])
print(M)

matrix_min = np.min(M)
col_min = np.min(M, axis=0)
row_min = np.min(M, axis=1)

print(matrix_min)
print(col_min)
print(row_min)

print("================")

matrix_min_idx = np.argmin(M)
col_min_idx = np.argmin(M, axis=0)
row_min_idx = np.argmin(M, axis=1)

print(matrix_min_idx)
print(col_min_idx)
print(row_min_idx)

[[ 0  1 10]
 [20  6  5]]
0
[0 1 5]
[0 5]
0
[0 0 1]
[0 2]


In [13]:
# vector (pytorch)
v = torch.tensor([1, 40, 2, -3])

minval_torch = torch.min(v)
maxval_torch = torch.max(v)

print(minval_torch, maxval_torch)

minidx_torch = torch.argmin(v)
maxidx_torch = torch.argmax(v)

print(minidx_torch, maxidx_torch)



tensor(-3) tensor(40)
tensor(3) tensor(1)


In [18]:
# matrix (pytorch)
M = torch.tensor([[0, 1, 10], [20, 6, 5]])
print(M)

matrix_min_torch = torch.min(M)
col_min_torch = torch.min(M, axis=0)
row_min_torch = torch.min(M, axis=1)

print("---------")
print(matrix_min_torch)
print("---------")
print(col_min_torch)
print("---------")
print(row_min_torch)

tensor([[ 0,  1, 10],
        [20,  6,  5]])
---------
tensor(0)
---------
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
---------
torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 2]))
